apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailappdeployment
spec:
  replicas: 1  # Desired number of pod replicas
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      labels:
        type: webserver
    spec:
      containers:
      - name:  retailapp-cont
        image: sonia1690/abc-techapp:lts  # Define the Docker image to use
